#! /usr/bin/env python
# -*- coding: utf-8 -*-
"""
@author: zhoujb
@contact: zhoujiebing@maimiaotech.com
@date: 2014-06-24 16:47
@version: 0.0.0
@license: Copyright maimiaotech.com
@copyright: Copyright maimiaotech.com

"""
class CampaignType(object):

    CAMPAIGN_GIVEUP = 1
    CAMPAIGN_LOW_TRAFFIC = 2
    CAMPAIGN_LOW_ROI = 3
    CAMPAIGN_OK = 4

    CAMPAIGN_OFF_LINE = 11
    CAMPAIGN_LESS_ADGROUPS = 12
　　CAMPAIGN_LOW_CPCMAX = 13
　　
　　CAMPAIGN_PLATFORM_CLOSE = 111
　　CAMPAIGN_PLATFORM_LOW_DISCOUNT = 112
　　CAMPAIGN_PLATFORM_LOW_ROI = 113
　　
　　CAMPAIGN_SCHEDULE_LOW_DISCOUNT = 121
　　CAMPAIGN_SCHEDULE_LOW_ROI = 122
　　
　　CAMPAIGN_AREA_LESS_CITY = 131
　　CAMPAIGN_AREA_LOW_ROI = 132
　　
　　CAMPAIGN_NONSEARCH_CLOSE = 141
　　CAMPAIGN_NONSEARCH_LOW_ROI = 142

class Adgroup_Type(object):
    
    ADGROUP_SMALL_CAT = 1
    ADGROUP_LESS_KEYWORD = 2
    ADGROUP_LOW_CPCMAX = 3
    ADGROUP_LOW_BID = 4
    ADGROUP_LOW_TRAFFIC = 5
    ADGROUP_LOW_CVR = 6
　　ADGROUP_HIGH_CPC_OF_BID = 7
　　ADGROUP_HIGH_CPC_OF_QSCORE = 8
    ADGROUP_LOW_RELATIVE_SCORE = 9
    ADGROUP_LOW_CREATIVE_SCORE = 10
　　ADGROUP_LOW_BASE_SCORE = 11
　　ADGROUP_LOW_CPC_MAX = 12
　　ADGROUP_LOW_CPC = 13

