#! /usr/bin/env python
# -*- coding: utf-8 -*-
"""
@author: zhoujb
@contact: zhoujiebing@maimiaotech.com
@date: 2014-06-24 16:47
@version: 0.0.0
@license: Copyright maimiaotech.com
@copyright: Copyright maimiaotech.com

"""
class CampaignType(object):
    CAMPAIGN_TEST_TWO = 9 
    CAMPAIGN_TEST = 10
    CAMPAIGN_GIVEUP = 11
    CAMPAIGN_LOW_CLICK = 12
    CAMPAIGN_LOW_ROI = 13
    CAMPAIGN_OK = 14
    CAMPAIGN_USER_WANT_AUCTION_KEYWORD = 15
    CAMPAIGN_USER_WANT_EXCHANGE_KEYWORD = 16
    CAMPAIGN_USER_WANT_ADD_KEYWORD = 17
    
    SHOP_IN_DEBT = 101     
    SHOP_BE_PUNISH = 102
    CAMPAIGN_BUDGET_OUT_LIMIT = 103
    CAMPAIGN_BUDGET_NEAR = 104

    CAMPAIGN_OFF_LINE = 111
    CAMPAIGN_LESS_ADGROUPS = 112 
    CAMPAIGN_LOW_BIDMAX = 113
    CAMPAIGN_LOW_LIMIT = 114
    CAMPAIGN_NO_CVR = 115

    CAMPAIGN_PLATFORM_CLOSE = 121
    CAMPAIGN_PLATFORM_PC_LOW_DISCOUNT = 122
    CAMPAIGN_PLATFORM_LOW_ROI = 123
    CAMPAIGN_PLATFORM_WX_LOW_DISCOUNT = 124
    CAMPAIGN_PLATFORM_NO_AUTHORITY = 125

    CAMPAIGN_SCHEDULE_LOW_DISCOUNT = 131
    CAMPAIGN_SCHEDULE_ROI_DIFF = 132
    CAMPAIGN_SCHEDULE_NO_AUTHORITY = 133

    CAMPAIGN_AREA_LESS_CITY = 141
    CAMPAIGN_AREA_LOW_ROI = 142
    
    CAMPAIGN_NO_ADGROUP = 151
    CAMPAIGN_NO_ADGROUP_HANDLE = 152
    CAMPAIGN_STOP = 153
    CAMPAIGN_NO_HANDLE = 154
    
    ALL_CAMPAIGN_TYPES = [
        CAMPAIGN_TEST,
        CAMPAIGN_TEST_TWO,
        CAMPAIGN_GIVEUP,
        CAMPAIGN_LOW_CLICK,
        CAMPAIGN_LOW_ROI,
        CAMPAIGN_OK,
        CAMPAIGN_NO_CVR,
        SHOP_IN_DEBT,     
        SHOP_BE_PUNISH,
        CAMPAIGN_BUDGET_OUT_LIMIT,
        CAMPAIGN_BUDGET_NEAR,
        CAMPAIGN_OFF_LINE,
        CAMPAIGN_LESS_ADGROUPS, 
        CAMPAIGN_LOW_BIDMAX,
        CAMPAIGN_LOW_LIMIT,
        CAMPAIGN_PLATFORM_CLOSE,
        CAMPAIGN_PLATFORM_PC_LOW_DISCOUNT,
        CAMPAIGN_PLATFORM_WX_LOW_DISCOUNT,
        CAMPAIGN_PLATFORM_NO_AUTHORITY,
        CAMPAIGN_PLATFORM_LOW_ROI,
        CAMPAIGN_SCHEDULE_LOW_DISCOUNT,
        CAMPAIGN_SCHEDULE_ROI_DIFF,
        CAMPAIGN_SCHEDULE_NO_AUTHORITY,

        CAMPAIGN_AREA_LESS_CITY,
        CAMPAIGN_AREA_LOW_ROI,
        
        CAMPAIGN_NO_ADGROUP,
        CAMPAIGN_NO_ADGROUP_HANDLE,
        CAMPAIGN_STOP,
        CAMPAIGN_NO_HANDLE
        ]
    
    CAMPAIGN_TYPES = [
        CAMPAIGN_GIVEUP,
        CAMPAIGN_LOW_CLICK,
        CAMPAIGN_LOW_ROI,
        CAMPAIGN_OK
        ]


class AdgroupType(object):
    
    ADGROUP_OK = 20
    ADGROUP_SMALL_CAT = 21
    ADGROUP_LESS_KEYWORD = 22
    ADGROUP_LOW_BIDMAX = 23
    ADGROUP_LOW_BID = 24
    ADGROUP_LOW_TRAFFIC = 25
    ADGROUP_LOW_CVR = 26                           
    ADGROUP_LACK_INFO = 27
    ADGROUP_HIGH_DISCOUNT = 28

    ADGROUP_LOW_ROI_CLICK_NOT_ENOUGH = 201
    ADGROUP_LOW_ROI_OF_HIGH_CPC = 202

    ADGROUP_LOW_RELATIVE_SCORE = 210
    ADGROUP_LOW_CREATIVE_SCORE = 211
    ADGROUP_LOW_BASE_SCORE = 212
    ADGROUP_LOW_CTR = 213
    ADGROUP_LOW_ROI_OF_HIGH_COST = 214
    ADGROUP_LOW_QSCORE = 215
    ADGROUP_LOW_CVR_SCORE = 216
    ADGROUP_LOW_RELATIVE_QUERY = 217

    ADGROUP_USER_INCREASE_COST = 220
    ADGROUP_USER_DECREASE_COST = 221

    ADGROUP_NONSEARCH_CLOSE = 230
    ADGROUP_NONSEARCH_LOW_ROI = 231
    ADGROUP_NONSEARCH_LOW_BID = 232
    
    ADGROUP_CPC_OPTIMIZE = 301
    ADGROUP_CLICK_OPTIMIZE = 302
    ADGROUP_PAY_OPTIMIZE = 303
    ADGROUP_ROI_OPTIMIZE = 304
    
    ADGROUP_CPC_OPTIMIZE_OK = 311
    ADGROUP_CLICK_OPTIMIZE_OK = 312
    ADGROUP_PAY_OPTIMIZE_OK = 313
    ADGROUP_ROI_OPTIMIZE_OK = 314

    ADGROUP_CPC_OPTIMIZE_NO_HOPE = 321
    ADGROUP_CLICK_OPTIMIZE_NO_HOPE = 322
    ADGROUP_PAY_OPTIMIZE_NO_HOPE = 323
    ADGROUP_ROI_OPTIMIZE_NO_HOPE = 324

    ADGROUP_UNKNOW = 400
    ADGROUP_LOW_PV_UNKNOW = 401
    
    ADGROUP_CVR_GRADE_1 = 241
    ADGROUP_CVR_GRADE_2 = 242
    ADGROUP_CVR_GRADE_3 = 243
    ADGROUP_CVR_GRADE_4 = 244
    ADGROUP_CVR_GRADE_5 = 245

    ALL_ADGROUP_TYPES = [
        ADGROUP_OK,
        ADGROUP_SMALL_CAT,
        ADGROUP_LESS_KEYWORD,
        ADGROUP_LOW_BIDMAX,
        ADGROUP_LOW_BID,
        ADGROUP_LOW_TRAFFIC,
        ADGROUP_LOW_CVR,                           
        ADGROUP_LACK_INFO,
        ADGROUP_HIGH_DISCOUNT,
        ADGROUP_LOW_ROI_CLICK_NOT_ENOUGH,
        ADGROUP_LOW_ROI_OF_HIGH_CPC,
        ADGROUP_LOW_RELATIVE_SCORE,
        ADGROUP_LOW_CREATIVE_SCORE,
        ADGROUP_LOW_BASE_SCORE,
        ADGROUP_LOW_CTR,
        ADGROUP_LOW_ROI_OF_HIGH_COST,
        ADGROUP_LOW_QSCORE,
        ADGROUP_LOW_CVR_SCORE,
        ADGROUP_LOW_RELATIVE_QUERY,
        ADGROUP_USER_INCREASE_COST,
        ADGROUP_USER_DECREASE_COST,
        ADGROUP_NONSEARCH_CLOSE,
        ADGROUP_NONSEARCH_LOW_ROI,
        ADGROUP_NONSEARCH_LOW_BID,
        ADGROUP_CPC_OPTIMIZE,
        ADGROUP_CLICK_OPTIMIZE,
        ADGROUP_PAY_OPTIMIZE,
        ADGROUP_ROI_OPTIMIZE,
        ADGROUP_CPC_OPTIMIZE_OK,
        ADGROUP_CLICK_OPTIMIZE_OK,
        ADGROUP_PAY_OPTIMIZE_OK,
        ADGROUP_ROI_OPTIMIZE_OK,
        ADGROUP_CPC_OPTIMIZE_NO_HOPE,
        ADGROUP_CLICK_OPTIMIZE_NO_HOPE,
        ADGROUP_PAY_OPTIMIZE_NO_HOPE,
        ADGROUP_ROI_OPTIMIZE_NO_HOPE,
        ADGROUP_UNKNOW,
        ADGROUP_LOW_PV_UNKNOW,
        ADGROUP_CVR_GRADE_1,
        ADGROUP_CVR_GRADE_2,
        ADGROUP_CVR_GRADE_3,
        ADGROUP_CVR_GRADE_4,
        ADGROUP_CVR_GRADE_5
        ]

    MACHINE_DIAGNOSE_TYPES = [
        ADGROUP_OK,
        ADGROUP_SMALL_CAT,
        ADGROUP_LESS_KEYWORD,
        ADGROUP_LOW_BIDMAX,
        ADGROUP_LOW_BID,
        ADGROUP_LOW_TRAFFIC,
        ADGROUP_LOW_CVR,                           
        ADGROUP_LACK_INFO,
        ADGROUP_HIGH_DISCOUNT,
        ADGROUP_LOW_ROI_CLICK_NOT_ENOUGH,
        ADGROUP_LOW_ROI_OF_HIGH_CPC,
        ADGROUP_LOW_RELATIVE_SCORE,
        ADGROUP_LOW_CREATIVE_SCORE,
        ADGROUP_LOW_BASE_SCORE,
        ADGROUP_LOW_CVR_SCORE,
        ADGROUP_LOW_RELATIVE_QUERY,
        ADGROUP_LOW_CTR,
        ADGROUP_LOW_ROI_OF_HIGH_COST,
        ADGROUP_LOW_QSCORE,
        ADGROUP_LOW_PV_UNKNOW,
        ]

CODE_TO_TYPE = {
        9:'CAMPAIGN_TEST_TWO'
        ,10:'CAMPAIGN_TEST'
        ,11:'CAMPAIGN_GIVEUP'
        ,12:'CAMPAIGN_LOW_CLICK'
        ,13:'CAMPAIGN_LOW_ROI'
        ,14:'CAMPAIGN_OK'
        ,101:'SHOP_IN_DEBT'
        ,102:'SHOP_BE_PUNISH'
        ,103:'CAMPAIGN_BUDGET_OUT_LIMIT'
        ,104:'CAMPAIGN_BUDGET_NEAR'
        ,111:'CAMPAIGN_OFF_LINE'
        ,112:'CAMPAIGN_LESS_ADGROUPS'
        ,113:'CAMPAIGN_LOW_BIDMAX'
        ,114:'CAMPAIGN_LOW_LIMIT'
        ,115:'CAMPAIGN_NO_CVR'
        ,121:'CAMPAIGN_PLATFORM_CLOSE'
        ,122:'CAMPAIGN_PLATFORM_PC_LOW_DISCOUNT'
        ,123:'CAMPAIGN_PLATFORM_LOW_ROI'
        ,124:'CAMPAIGN_PLATFORM_WX_LOW_DISCOUNT'
        ,125:'CAMPAIGN_PLATFORM_NO_AUTHORITY'
        ,131:'CAMPAIGN_SCHEDULE_LOW_DISCOUNT'
        ,132:'CAMPAIGN_SCHEDULE_ROI_DIFF'
        ,133:'CAMPAIGN_SCHEDULE_NO_AUTHORITY'
        ,141:'CAMPAIGN_AREA_LESS_CITY'
        ,142:'CAMPAIGN_AREA_LOW_ROI'
        ,151:'CAMPAIGN_NO_ADGROUP'
        ,152:'CAMPAIGN_NO_ADGROUP_HANDLE'
        ,153:'CAMPAIGN_STOP'
        ,154:'CAMPAIGN_NO_HANDLE'
        ,20:'ADGROUP_OK'
        ,21:'ADGROUP_SMALL_CAT'
        ,22:'ADGROUP_LESS_KEYWORD'
        ,23:'ADGROUP_LOW_BIDMAX'
        ,24:'ADGROUP_LOW_BID'
        ,25:'ADGROUP_LOW_TRAFFIC'
        ,26:'ADGROUP_LOW_CVR'
        ,27:'ADGROUP_LACK_INFO'
        ,28:'ADGROUP_HIGH_DISCOUNT'
        ,201:'ADGROUP_LOW_ROI_CLICK_NOT_ENOUGH'
        ,202:'ADGROUP_LOW_ROI_OF_HIGH_CPC'
        ,210:'ADGROUP_LOW_RELATIVE_SCORE'
        ,211:'ADGROUP_LOW_CREATIVE_SCORE'
        ,212:'ADGROUP_LOW_BASE_SCORE'
        ,213:'ADGROUP_LOW_CTR'
        ,214:'ADGROUP_LOW_ROI_OF_HIGH_COST'
        ,215:'ADGROUP_LOW_QSCORE'
        ,216:'ADGROUP_LOW_CVR_SCORE'
        ,217:'ADGROUP_LOW_RELATIVE_QUERY'
        ,220:'ADGROUP_USER_INCREASE_COST'
        ,221:'ADGROUP_USER_DECREASE_COST'
        ,230:'ADGROUP_NONSEARCH_CLOSE'
        ,231:'ADGROUP_NONSEARCH_LOW_ROI'
        ,232:'ADGROUP_NONSEARCH_LOW_BID'
        ,301:'ADGROUP_CPC_OPTIMIZE'
        ,302:'ADGROUP_CLICK_OPTIMIZE'
        ,303:'ADGROUP_PAY_OPTIMIZE'
        ,304:'ADGROUP_ROI_OPTIMIZE'
        ,311:'ADGROUP_CPC_OPTIMIZE_OK'
        ,312:'ADGROUP_CLICK_OPTIMIZE_OK'
        ,313:'ADGROUP_PAY_OPTIMIZE_OK'
        ,314:'ADGROUP_ROI_OPTIMIZE_OK'
        ,321:'ADGROUP_CPC_OPTIMIZE_NO_HOPE'
        ,322:'ADGROUP_CLICK_OPTIMIZE_NO_HOPE'
        ,323:'ADGROUP_PAY_OPTIMIZE_NO_HOPE'
        ,324:'ADGROUP_ROI_OPTIMIZE_NO_HOPE'
        ,400:'ADGROUP_UNKNOW'
        ,401:'ADGROUP_LOW_PV_UNKNOW'
        ,241:'ADGROUP_CVR_GRADE_1'
        ,242:'ADGROUP_CVR_GRADE_2'
        ,243:'ADGROUP_CVR_GRADE_3'
        ,244:'ADGROUP_CVR_GRADE_4'
        ,245:'ADGROUP_CVR_GRADE_5'
        ,'None_11':'None->CAMPAIGN_GIVEUP'
        ,'None_12':'None->CAMPAIGN_LOW_CLICK'
        ,'None_13':'None->CAMPAIGN_LOW_ROI'
        ,'None_14':'None->CAMPAIGN_OK'
        ,'11_11':'CAMPAIGN_GIVEUP->CAMPAIGN_GIVEUP'
        ,'11_12':'CAMPAIGN_GIVEUP->CAMPAIGN_LOW_CLICK'
        ,'11_13':'CAMPAIGN_GIVEUP->CAMPAIGN_LOW_ROI'
        ,'11_14':'CAMPAIGN_GIVEUP->CAMPAIGN_OK'
        ,'12_11':'CAMPAIGN_LOW_CLICK->CAMPAIGN_GIVEUP'
        ,'12_12':'CAMPAIGN_LOW_CLICK->CAMPAIGN_LOW_CLICK'
        ,'12_13':'CAMPAIGN_LOW_CLICK->CAMPAIGN_LOW_ROI'
        ,'12_14':'CAMPAIGN_LOW_CLICK->CAMPAIGN_OK'
        ,'13_11':'CAMPAIGN_LOW_ROI->CAMPAIGN_GIVEUP'
        ,'13_12':'CAMPAIGN_LOW_ROI->CAMPAIGN_LOW_CLICK'
        ,'13_13':'CAMPAIGN_LOW_ROI->CAMPAIGN_LOW_ROI'
        ,'13_14':'CAMPAIGN_LOW_ROI->CAMPAIGN_OK'
        ,'14_11':'CAMPAIGN_OK->CAMPAIGN_GIVEUP'
        ,'14_12':'CAMPAIGN_OK->CAMPAIGN_LOW_CLICK'
        ,'14_13':'CAMPAIGN_OK->CAMPAIGN_LOW_ROI'
        ,'14_14':'CAMPAIGN_OK->CAMPAIGN_OK'
        }

CAMPAIGN_GIVEUP_REASON = {
        CampaignType.CAMPAIGN_NO_ADGROUP:"计划内无推广组"
        ,CampaignType.CAMPAIGN_NO_ADGROUP_HANDLE:"计划内无推广组托管"
        ,CampaignType.CAMPAIGN_STOP:"计划暂停"
        ,CampaignType.CAMPAIGN_NO_HANDLE:"计划未托管"
        ,CampaignType.SHOP_IN_DEBT:"店铺欠费"
        ,CampaignType.SHOP_BE_PUNISH:"店铺直通车违禁"
        ,CampaignType.CAMPAIGN_BUDGET_OUT_LIMIT:"预算超出版本限制"
        }

CAMPAIGN_LOW_CLICK_REASON = {
        CampaignType.CAMPAIGN_PLATFORM_CLOSE:"计划站外或无线未开起"
        ,CampaignType.CAMPAIGN_PLATFORM_PC_LOW_DISCOUNT:"计划站外PC折扣设置过低"
        ,CampaignType.CAMPAIGN_PLATFORM_WX_LOW_DISCOUNT:"计划站外WX折扣设置过低"
        ,CampaignType.CAMPAIGN_SCHEDULE_LOW_DISCOUNT:"计划分时折扣过低"
        ,CampaignType.CAMPAIGN_AREA_LESS_CITY:"计划地域勾选过少"
        ,CampaignType.CAMPAIGN_OFF_LINE:"计划提前下线"
        ,CampaignType.CAMPAIGN_LESS_ADGROUPS:"推广组不足"
        ,CampaignType.CAMPAIGN_LOW_BIDMAX:"计划最高出价设置过低"

        ,AdgroupType.ADGROUP_NONSEARCH_CLOSE:"推广组定向未开起"
        ,AdgroupType.ADGROUP_LOW_CREATIVE_SCORE:"推广组创意不佳"
        ,AdgroupType.ADGROUP_LOW_BASE_SCORE:"推广组基础分低"
        ,AdgroupType.ADGROUP_LOW_RELATIVE_SCORE:"推广组相关性低"
        ,AdgroupType.ADGROUP_SMALL_CAT:"宝贝属于小类目"
        ,AdgroupType.ADGROUP_LACK_INFO:"宝贝标题和属性信息过少"
        ,AdgroupType.ADGROUP_LESS_KEYWORD:"推广组内关键词过少"
        ,AdgroupType.ADGROUP_LOW_BIDMAX:"推广组最高出价设置过低"
        ,AdgroupType.ADGROUP_LOW_BID:"推广组关键词出价过低"
        ,AdgroupType.ADGROUP_LOW_TRAFFIC:"推广组关键词偏冷"
        ,AdgroupType.ADGROUP_LOW_CTR:"推广组点击率低"

        }


CAMPAIGN_LOW_ROI_REASON = {
        CampaignType.CAMPAIGN_OFF_LINE:"计划提前下线"
        ,CampaignType.CAMPAIGN_PLATFORM_LOW_ROI:"计划站外或无线ROI过低"
        ,CampaignType.CAMPAIGN_SCHEDULE_ROI_DIFF:"计划分时折扣设置不合理"
        ,CampaignType.CAMPAIGN_AREA_LOW_ROI:"计划地域设置不合理"
        
        ,AdgroupType.ADGROUP_NONSEARCH_LOW_ROI:"推广组定向出价不合理"
        ,AdgroupType.ADGROUP_NONSEARCH_LOW_BID:"推广组定向出价过低"
        ,AdgroupType.ADGROUP_LOW_CVR:"宝贝转化率低"
        ,AdgroupType.ADGROUP_LOW_ROI_CLICK_NOT_ENOUGH:"ROI低推广组点击不充分"
        ,AdgroupType.ADGROUP_LOW_ROI_OF_HIGH_CPC:"ROI低推广组CPC过高"
        ,AdgroupType.ADGROUP_LOW_ROI_OF_HIGH_COST:"ROI低推广组花费过高"
        }                

