#encoding=utf8
__author__ = 'chenke'


class ExtendType(object):
    DEFAULT = 0
    PV_FIRST = 1
    CONV_FIRST = 2
    MONEY_FIRST = 3
    REL_AND_PV = 4

class PlatformId(object):
    pc_in = 1
    pc_out = 2
    wx_in = 8
    wx_out = 16

    CODE_TO_STR = {
            1:'pc_in',
            2:'pc_out',
            4:'pc_out',
            8:'wx_in',
            16:'wx_out'
            }
    
class WordDeleteType(object):
    AUDIT_UNPASS = 1
    LOW_QSCORE = 2
    LOW_PV_OLD = 3
    SPECIAL_FILTER = 4
    DELETE_PERCENT = 5
    LOW_CLICK_OLD = 6
    IS_GARBAGE = 7

    USER_DELETE = 10
    LOW_PV_MAX_PRICE = 11
    LOW_PV_BEST_POSITION = 12
    
    FILTER_WORDS = 13
    LOW_RELEVANCE = 14

    USER_DELETE_TAOBAO = 15

class OperationType(object):

    DELETE_UNEXPECT = -1
    DELETE_AUDIT_UNPASS = 1
    DELETE_LOW_QSCORE = 2
    DELETE_LOW_PV_OLD = 3
    DELETE_DELETE_PERCENT = 4
    DELETE_LOW_CLICK_OLD = 5
    #DELETE_IS_GARGABE = 6
    DELETE_IS_GARBAGE = 6
    DELETE_USER_DELETE = 7
    DELETE_LOW_PV_MAX_PRICE = 8
    DELETE_LOW_PV_BEST_POSITION = 9
    DELETE_FILTER_WORDS = 10
    DELETE_LOW_RELEVANCE = 11
    DELETE_DIRECTOR = 12
    DELETE_HISTORY_NORMAL = 13
    DELETE_LOW_PV_BY_ADGROUP_CPC = 15
    DELETE_USER_DELETE_TAOBAO = 16
    DELETE_GARBAGE_MAX_PRICE = 17
    DELETE_MANUAL_ADGROUP = 18

    #分层新增
    DELETE_LOW_CTR = 19 
    DELETE_LOW_ROI = 20
    DELETE_LOW_CUST_SCORE = 21
    DELETE_LOW_PV = 22
    DELETE_IS_GARBAGE_BY_USER = 23


    UPDATE_PRICE_ROI_GOOD_INCRE_PRICE = 101
    UPDATE_PRICE_ROI_PREDICT_GOOD_INCRE_PRICE = 102
    UPDATE_PRICE_ROI_BAD_DECRE_PRICE = 103
    UPDATE_PRICE_COST_SUFF_INCRE_PRICE = 104
    UPDATE_PRICE_COST_FULL_DECRE_PRICE = 105
    UPDATE_PRICE_GARBAGE_INCRE_PRICE = 106
    UPDATE_PRICE_MINIMIZE_CPC_MAX = 107
    UPDATE_PRICE_TO_INCREASE_COST = 108
    UPDATE_PRICE_TO_DECREASE_COST = 109
    UPDATE_PRICE_TO_APPROVE_ROI = 110
    UPDATE_PRICE_DIRECTOR = 111
    UPDATE_PRICE_HISTORY_NORMAL = 112 
    UPDATE_PRICE_COST_LESS_THAN_LIMIT_INCRE_PRICE = 113 
    UPDATE_PRICE_CUSTOM = 114 
    UPDATE_PRICE_FOR_CPC_MAX = 115 
    UPDATE_PRICE_GOOD_POSITION_INCRE_PRICE = 120
    UPDATE_PRICE_GOOD_POSITION_DECRE_PRICE = 121
    UPDATE_PRICE_HOT_INCRE_CLICK_INCRE_PRICE = 122
    UPDATE_PRICE_HOT_DECRE_CLICK_DECRE_PRICE = 123
    UPDATE_PRICE_HOT_COST_FULL_DECRE_PRICE = 124 
    UPDATE_PRICE_MANUAL_ADGROUP = 127
    UPDATE_PRICE_BUDGET_CONTROL_LOW_PRICE = 137
    UPDATE_PRICE_BUDGET_CONTROL_ORIGINAL_PRICE = 138
    UPDATE_PRICE_PC_WIDE_MATCH = 139

    #分层优化新增   
    UPDATE_PRICE_ACCURATE_MATCH = 125
    UPDATE_PRICE_WIDE_MATCH = 126
    UPDATE_PRICE_USER_EXPECT_INCRE_PRICE = 128 
    UPDATE_PRICE_USER_EXPECT_DECRE_PRICE = 129 
    UPDATE_PRICE_ITEM_GOOD_INCRE_PRICE = 130
    UPDATE_PRICE_ITEM_BAD_DECRE_PRICE = 131
    UPDATE_PRICE_NOCLICK_INCRE_PRICE = 132
    SET_PC_KEYWORDS_MODEL = 133
    SET_WX_KEYWORDS_MODEL = 134
    UPDATE_PC_RANK_CPC_MAX = 135
    UPDATE_WX_RANK_CPC_MAX = 136

    KEEP_NORMAL = 201
    
    #无线改价新增
    UPDATE_KEYWORD_MOBILE_PRICE_NORMAL = 210
    UPDATE_PRICE_MOBILE_ROI_GOOD_INCRE_PRICE = 211
    UPDATE_PRICE_MOBILE_ROI_BAD_DECRE_PRICE = 212
    UPDATE_PRICE_MOBILE_GARBAGE_INCRE_PRICE = 213
    UPDATE_PRICE_MOBILE_GOOD_POSITION_INCRE_PRICE = 214
    UPDATE_PRICE_MOBILE_GOOD_POSITION_DECRE_PRICE = 215
    UPDATE_PRICE_MOBILE_BUDGET_CONTROL_LOW_PRICE = 216
    UPDATE_PRICE_MOBILE_BUDGET_CONTROL_ORIGINAL_PRICE = 217
    UPDATE_PRICE_MOBILE_COST_FULL_DECRE_PRICE = 218
    UPDATE_PRICE_MOBILE_COST_SUFF_DECRE_PRICE = 219
    UPDATE_PRICE_MOBILE_TO_INCREASE_COST = 220
    UPDATE_PRICE_MOBILE_TO_DECREASE_COST = 221
    UPDATE_PRICE_MOBILE_NOCLICK_INCRE_PRICE = 222
    UPDATE_PRICE_MOBILE_ROI_PREDICT_GOOD_INCRE_PRICE = 223
    UPDATE_PRICE_MOBILE_CUSTOM = 224
    UPDATE_PRICE_MOBILE_WIDE_MATCH = 225

    IGNORE_KEYWORD_NOT_EXIST = 301
    IGNORE_KEYWORD_NOT_HANDLE = 302
    IGNORE_NOT_MANAGE_BY_SOFT = 303
    IGNORE_CREATE_TIME_SHORT = 304
    IGNORE_MODIFIED_TIME_SHORT = 305
    IGNORE_KEYWORD_REPORT_NONE = 306
    IGNORE_CAMPAIGN_REPORT_NONE = 307
    IGNORE_CAMPAIGN_STOPPED = 308
    IGNORE_ADGROUP_REPORT_NONE = 309

    IGNORE_CAMPAIGN_OFFLINE = 310
    IGNORE_CAMPAIGN_SETTINGS_NONE = 311
    IGNORE_CAMPAIGN_INIT_FAILED = 312
    IGNORE_CAMPAIGN_CANCEL_OPTIMIZE = 313
    IGNORE_CAMPAIGN_LOW_IMPRESSIONS = 314
    IGNORE_ADGROUP_TOO_MUCH = 315
    
    IGNORE_PLATFORM_UNHANDLE = 316
    IGNORE_PLATFORM_CAMPAIGN_CANCEL_OPTIMIZE = 317
    IGNORE_PLATFORM_CAMPAIGN_LOW_COST = 318
    IGNORE_PLATFORM_CAMPAIGN_OFFLINE =319
    IGNORE_SCHEDULE_UNHANDLE = 320
    IGNORE_SCHEDULE_REPORT_FAILED = 321
    IGNORE_PLATFORM_REPORT_FAILED = 322
    IGNORE_CAMPAIGN_PLATFORM_NORMAL = 325
    CAMPAIGN_SCHEDULE_OPTIMIZE = 323
    CAMPAIGN_PLATFORM_OPTIMIZE = 324
    IGNORE_CAMPAIGN_GIVE_UP = 326
    IGNORE_ADGROUP_NOT_INCREASE_COST = 327
    IGNORE_ADGROUP_NOT_DECREASE_COST =328
    IGNORE_CAMPAIGN_BUDGET_OUT_LIMIT = 329
    CHANGE_CAMPAIGN_PLATFORM_PC_DISCOUNT = 330
    CHANGE_CAMPAIGN_PLATFORM_WX_DISCOUNT = 331
    OPEN_CAMPAIGN_PLATFORM_OPTIMIZE = 332
    CLOSE_CAMPAIGN_PLATFORM_OPTIMIZE = 333

    ADD_NEW_CAMPAIGN_SETTINGS = 334
    IGNORE_CAMPAIGN_NO_ADGROUP = 335
    IGNORE_SHOP_IN_DEBT = 336
    IGNORE_RT_OPTIMIZE_OFFLINE = 337

    ADD_NORMAL = 401
    ADD_KEYWORD_NORMAL = 402
    ADD_KEYWORD_INITIAL = 403
    ADD_KEYWORD_DIRECTOR = 404
    ADD_KEYWORD_HISTORY_NORMAL = 405
    ADD_KEYWORD_EXTRA_INFO = 406

    ADD_ADGROUP_NORMAL = 501
    DELETE_ADGROUP_NORMAL = 502
    DELETE_ADGROUP_INITIAL = 503
    DELETE_ADGROUP_HISTORY_NORMAL = 504

    START_ADGROUP= 510
    START_OPTIMIZE_ADGROUP = 511
    STOP_ADGROUP = 512
    STOP_OPTIMIZE_ADGROUP = 513
    START_OPTIMIZE_ADGROUP_ONLY_PRICE = 514
    RISE_ADGROUP_CPC_MAX = 515
    DROP_ADGROUP_CPC_MAX = 516
    DELETE_CREATIVE_NORMAL = 517
    ADD_CREATIVE_NORMAL = 518
    MODIFY_CREATIVE_NORMAL = 519

    ADD_CAMPAIGN_NORMAL = 601
    START_CAMPAIGN = 610
    START_OPTIMIZE_CAMPAIGN = 611
    START_OPTIMIZE_CAMPAIGN_ITEM_LABEL = 621
    STOP_CAMPAIGN = 612
    STOP_OPTIMIZE_CAMPAIGN = 613
    STOP_OPTIMIZE_CAMPAIGN_ITEM_LABEL = 623
    START_ITEM_AUTO_STATUS = 624
    STOP_ITEM_AUTO_STATUS =  625
    CHANGE_ITEM_LABEL = 626


    UPGRADE_CAMPAIGN = 614
    CHANGE_CAMPAIGN_SETTINGS = 700
    CHANGE_ADGROUP_SETTINGS = 701
    CHANGE_ADGROUP_MOBILE_DISCOUNT = 702
    CHANGE_CAMPAIGN_WX_CPC_MAX = 705
    CHANGE_ADGROUP_WX_CPC_MAX = 706
    UPDATE_PRICE_FOR_PC_CPC_MAX = 707 
    UPDATE_PRICE_FOR_WX_CPC_MAX = 708
    CHANGE_ADGROUP_BUDGET = 709
    #人群相关操作
    STOP_CROWD_OPTIMIZE = 710
    STOP_CROWD = 711
    START_CROWD_OPTIIMIZE = 712
    START_CROWD = 713
    UPDATE_CROWD_DISCOUNT = 714 
    DELETE_CROWD = 715 
    ADD_CROWD = 716
    FOLLOW_CAMPAIGN = 720
    UPDATE_CAMPAIGN_BUDGET = 721
    UPDATE_CAMPAIGN_MODEL = 722


    ADD_RULE = 800
    UPDATE_RULE = 801
    DELETE_RULE = 802
    ENABLED_RULE = 803
    DISABLED_RULE = 804
    EXECUTE_RULE = 805
    EXECUTE_RULE_NOTICE = 806

    ALL_DELETE_TYPES = [
        DELETE_AUDIT_UNPASS,
        DELETE_LOW_QSCORE,
        DELETE_LOW_PV_OLD,
        DELETE_DELETE_PERCENT,
        DELETE_LOW_CLICK_OLD,
        DELETE_IS_GARBAGE,
        DELETE_USER_DELETE,
        DELETE_LOW_PV_MAX_PRICE,
        DELETE_LOW_PV_BEST_POSITION,
        DELETE_FILTER_WORDS,
        DELETE_LOW_RELEVANCE,
        DELETE_DIRECTOR,
        DELETE_HISTORY_NORMAL,
        DELETE_LOW_PV_BY_ADGROUP_CPC,
        DELETE_USER_DELETE_TAOBAO,
        DELETE_GARBAGE_MAX_PRICE,
        DELETE_CROWD,

        DELETE_ADGROUP_NORMAL,
        DELETE_ADGROUP_INITIAL,
        DELETE_ADGROUP_HISTORY_NORMAL,
        DELETE_MANUAL_ADGROUP,
        DELETE_LOW_CTR ,
        DELETE_LOW_ROI ,
        DELETE_LOW_PV,
        DELETE_IS_GARBAGE_BY_USER,
        DELETE_LOW_CUST_SCORE 
    ]

    ALL_UPDATE_TYPES = [
        UPDATE_PRICE_ROI_GOOD_INCRE_PRICE,
        UPDATE_PRICE_ITEM_GOOD_INCRE_PRICE,
        UPDATE_PRICE_ITEM_BAD_DECRE_PRICE,
        UPDATE_PRICE_ROI_PREDICT_GOOD_INCRE_PRICE,
        UPDATE_PRICE_ROI_BAD_DECRE_PRICE,
        UPDATE_PRICE_COST_SUFF_INCRE_PRICE, 
        UPDATE_PRICE_COST_FULL_DECRE_PRICE,
        UPDATE_CAMPAIGN_BUDGET,
        UPDATE_CAMPAIGN_MODEL,
        UPDATE_PRICE_GARBAGE_INCRE_PRICE,
        UPDATE_PRICE_NOCLICK_INCRE_PRICE,
        UPDATE_PRICE_MINIMIZE_CPC_MAX,
        UPDATE_PRICE_TO_INCREASE_COST,
        UPDATE_PRICE_TO_DECREASE_COST,
        UPDATE_PRICE_TO_APPROVE_ROI,
        UPDATE_PRICE_DIRECTOR,
        UPDATE_PRICE_HISTORY_NORMAL,
        UPDATE_KEYWORD_MOBILE_PRICE_NORMAL,
        UPDATE_PRICE_COST_LESS_THAN_LIMIT_INCRE_PRICE,
        UPDATE_PRICE_CUSTOM,
        UPDATE_PRICE_GOOD_POSITION_INCRE_PRICE,
        UPDATE_PRICE_GOOD_POSITION_DECRE_PRICE,
        UPDATE_PRICE_HOT_INCRE_CLICK_INCRE_PRICE,
        UPDATE_PRICE_HOT_DECRE_CLICK_DECRE_PRICE,
        UPDATE_PRICE_HOT_COST_FULL_DECRE_PRICE,
        UPDATE_PRICE_USER_EXPECT_INCRE_PRICE,
        UPDATE_PRICE_USER_EXPECT_DECRE_PRICE,
        UPDATE_PRICE_FOR_CPC_MAX,
        UPDATE_PRICE_ACCURATE_MATCH,
        UPDATE_PRICE_WIDE_MATCH,
        UPDATE_PRICE_MANUAL_ADGROUP,
        UPDATE_PRICE_MOBILE_GARBAGE_INCRE_PRICE,
        UPDATE_PRICE_MOBILE_ROI_GOOD_INCRE_PRICE,
        UPDATE_PRICE_MOBILE_ROI_BAD_DECRE_PRICE,
        UPDATE_PRICE_MOBILE_GOOD_POSITION_INCRE_PRICE,
        UPDATE_PRICE_MOBILE_GOOD_POSITION_DECRE_PRICE,
        UPDATE_PRICE_MOBILE_BUDGET_CONTROL_LOW_PRICE,
        UPDATE_PRICE_MOBILE_BUDGET_CONTROL_ORIGINAL_PRICE,
        UPDATE_PRICE_BUDGET_CONTROL_LOW_PRICE,
        UPDATE_PRICE_BUDGET_CONTROL_ORIGINAL_PRICE,
        UPDATE_PRICE_MOBILE_COST_FULL_DECRE_PRICE,
        UPDATE_PRICE_MOBILE_COST_SUFF_DECRE_PRICE,
        UPDATE_PRICE_MOBILE_TO_INCREASE_COST,
        UPDATE_PRICE_MOBILE_TO_DECREASE_COST,
        UPDATE_PRICE_MOBILE_NOCLICK_INCRE_PRICE,
        UPDATE_PRICE_MOBILE_ROI_PREDICT_GOOD_INCRE_PRICE,
        UPDATE_PRICE_MOBILE_CUSTOM,
        UPDATE_PRICE_MOBILE_WIDE_MATCH,
        UPDATE_PRICE_PC_WIDE_MATCH,
        CHANGE_CAMPAIGN_WX_CPC_MAX,
        CHANGE_ADGROUP_WX_CPC_MAX,
        CHANGE_ADGROUP_BUDGET,
        FOLLOW_CAMPAIGN,
        SET_PC_KEYWORDS_MODEL,
        SET_WX_KEYWORDS_MODEL,

        START_ADGROUP,
        START_OPTIMIZE_ADGROUP,
        STOP_ADGROUP,
        STOP_OPTIMIZE_ADGROUP,
        START_OPTIMIZE_ADGROUP_ONLY_PRICE,
        RISE_ADGROUP_CPC_MAX,
        DROP_ADGROUP_CPC_MAX,

        START_CAMPAIGN,
        START_OPTIMIZE_CAMPAIGN,
        START_OPTIMIZE_CAMPAIGN_ITEM_LABEL,
        STOP_CAMPAIGN,
        STOP_OPTIMIZE_CAMPAIGN,
        STOP_OPTIMIZE_CAMPAIGN_ITEM_LABEL,
        START_ITEM_AUTO_STATUS,
        STOP_ITEM_AUTO_STATUS,
        CHANGE_ITEM_LABEL,
        UPGRADE_CAMPAIGN,

        START_CROWD_OPTIIMIZE,START_CROWD,STOP_CROWD_OPTIMIZE,STOP_CROWD,UPDATE_CROWD_DISCOUNT,
        
        CAMPAIGN_SCHEDULE_OPTIMIZE ,
        CAMPAIGN_PLATFORM_OPTIMIZE,
        CHANGE_CAMPAIGN_PLATFORM_PC_DISCOUNT,
        CHANGE_CAMPAIGN_PLATFORM_WX_DISCOUNT,
        OPEN_CAMPAIGN_PLATFORM_OPTIMIZE,
        CLOSE_CAMPAIGN_PLATFORM_OPTIMIZE,
        CHANGE_CAMPAIGN_SETTINGS,
        CHANGE_ADGROUP_SETTINGS,
        CHANGE_ADGROUP_MOBILE_DISCOUNT
    ]


    ALL_ADD_TYPES = [
        ADD_NORMAL,
        ADD_KEYWORD_NORMAL,
        ADD_KEYWORD_INITIAL,
        ADD_KEYWORD_DIRECTOR,
        ADD_KEYWORD_HISTORY_NORMAL,
        ADD_KEYWORD_EXTRA_INFO,
        ADD_CROWD,

        ADD_ADGROUP_NORMAL,

        ADD_CAMPAIGN_NORMAL,
        ADD_NEW_CAMPAIGN_SETTINGS
    ]

    ALL_IGNORE_TYPES = [
        KEEP_NORMAL,
        IGNORE_KEYWORD_NOT_EXIST,
        IGNORE_KEYWORD_NOT_HANDLE,
        IGNORE_NOT_MANAGE_BY_SOFT,
        IGNORE_CREATE_TIME_SHORT,
        IGNORE_MODIFIED_TIME_SHORT,
        IGNORE_KEYWORD_REPORT_NONE,
        IGNORE_CAMPAIGN_REPORT_NONE,
        IGNORE_CAMPAIGN_STOPPED,
        IGNORE_ADGROUP_REPORT_NONE,

        IGNORE_CAMPAIGN_OFFLINE,
        IGNORE_CAMPAIGN_SETTINGS_NONE,
        IGNORE_CAMPAIGN_INIT_FAILED,
        IGNORE_CAMPAIGN_CANCEL_OPTIMIZE,
        IGNORE_CAMPAIGN_LOW_IMPRESSIONS,
        IGNORE_ADGROUP_TOO_MUCH,


        IGNORE_PLATFORM_UNHANDLE, 
        IGNORE_PLATFORM_CAMPAIGN_CANCEL_OPTIMIZE ,
        IGNORE_PLATFORM_CAMPAIGN_LOW_COST ,
        IGNORE_PLATFORM_CAMPAIGN_OFFLINE ,
        IGNORE_SCHEDULE_UNHANDLE,
        IGNORE_PLATFORM_REPORT_FAILED,
        IGNORE_SCHEDULE_REPORT_FAILED,
        IGNORE_CAMPAIGN_PLATFORM_NORMAL,
        IGNORE_CAMPAIGN_GIVE_UP,
        IGNORE_CAMPAIGN_BUDGET_OUT_LIMIT,
        IGNORE_CAMPAIGN_NO_ADGROUP, 
        IGNORE_SHOP_IN_DEBT,
        IGNORE_RT_OPTIMIZE_OFFLINE,

        IGNORE_ADGROUP_NOT_INCREASE_COST,
        IGNORE_ADGROUP_NOT_DECREASE_COST
    ]

    ALL_KEYWORD_ADD_TYPES = [
        ADD_NORMAL,
        ADD_KEYWORD_NORMAL,
        ADD_KEYWORD_INITIAL,
        ADD_KEYWORD_DIRECTOR,
        ADD_KEYWORD_HISTORY_NORMAL,
        ADD_KEYWORD_EXTRA_INFO
    ]


    ALL_KEYWORD_DELETE_TYPES = [
        DELETE_UNEXPECT,
        DELETE_AUDIT_UNPASS,
        DELETE_LOW_QSCORE,
        DELETE_LOW_PV_OLD,
        DELETE_DELETE_PERCENT,
        DELETE_LOW_CLICK_OLD,
        DELETE_IS_GARBAGE,
        DELETE_USER_DELETE,
        DELETE_LOW_PV_MAX_PRICE,
        DELETE_LOW_PV_BEST_POSITION,
        DELETE_FILTER_WORDS,
        DELETE_LOW_RELEVANCE,
        DELETE_DIRECTOR,
        DELETE_HISTORY_NORMAL,
        DELETE_LOW_PV_BY_ADGROUP_CPC,
        DELETE_USER_DELETE_TAOBAO,
        DELETE_GARBAGE_MAX_PRICE,
        DELETE_LOW_CTR ,
        DELETE_LOW_ROI ,
        DELETE_LOW_PV,
        DELETE_IS_GARBAGE_BY_USER,
        DELETE_LOW_CUST_SCORE
    ]

    ALL_KEYWORD_UPDATE_TYPES = [
        UPDATE_PRICE_ROI_GOOD_INCRE_PRICE,
        UPDATE_PRICE_ITEM_GOOD_INCRE_PRICE, #nouse
        UPDATE_PRICE_ITEM_BAD_DECRE_PRICE,  #nouse
        UPDATE_PRICE_ROI_PREDICT_GOOD_INCRE_PRICE,
        UPDATE_PRICE_ROI_BAD_DECRE_PRICE,
        UPDATE_PRICE_COST_SUFF_INCRE_PRICE, #nouse
        UPDATE_PRICE_COST_FULL_DECRE_PRICE,
        UPDATE_PRICE_GARBAGE_INCRE_PRICE,
        UPDATE_PRICE_NOCLICK_INCRE_PRICE,
        UPDATE_PRICE_MINIMIZE_CPC_MAX,
        UPDATE_PRICE_TO_INCREASE_COST,
        UPDATE_PRICE_TO_DECREASE_COST,
        UPDATE_PRICE_TO_APPROVE_ROI,#nouse
        UPDATE_PRICE_DIRECTOR,#nouse
        UPDATE_PRICE_HISTORY_NORMAL,
        UPDATE_KEYWORD_MOBILE_PRICE_NORMAL,
        UPDATE_PRICE_COST_LESS_THAN_LIMIT_INCRE_PRICE,#nouse
        UPDATE_PRICE_CUSTOM,
        UPDATE_PRICE_GOOD_POSITION_INCRE_PRICE,
        UPDATE_PRICE_GOOD_POSITION_DECRE_PRICE,
        UPDATE_PRICE_HOT_INCRE_CLICK_INCRE_PRICE,#nouse
        UPDATE_PRICE_HOT_DECRE_CLICK_DECRE_PRICE,#nouse
        UPDATE_PRICE_HOT_COST_FULL_DECRE_PRICE,#nouse
        UPDATE_PRICE_USER_EXPECT_INCRE_PRICE,#nouse
        UPDATE_PRICE_USER_EXPECT_DECRE_PRICE,#nouse
        UPDATE_PRICE_FOR_CPC_MAX,
        UPDATE_PRICE_ACCURATE_MATCH,#nouse
        UPDATE_PRICE_WIDE_MATCH,
        UPDATE_PRICE_FOR_PC_CPC_MAX,
        UPDATE_PRICE_FOR_WX_CPC_MAX,
        UPDATE_PRICE_MOBILE_GARBAGE_INCRE_PRICE,
        UPDATE_PRICE_MOBILE_ROI_GOOD_INCRE_PRICE,
        UPDATE_PRICE_MOBILE_ROI_BAD_DECRE_PRICE,
        UPDATE_PRICE_MOBILE_GOOD_POSITION_INCRE_PRICE,
        UPDATE_PRICE_MOBILE_GOOD_POSITION_DECRE_PRICE,
        UPDATE_PRICE_MOBILE_BUDGET_CONTROL_LOW_PRICE,
        UPDATE_PRICE_MOBILE_BUDGET_CONTROL_ORIGINAL_PRICE,
        UPDATE_PRICE_BUDGET_CONTROL_ORIGINAL_PRICE,
        UPDATE_PRICE_BUDGET_CONTROL_LOW_PRICE,
        UPDATE_PRICE_MOBILE_COST_FULL_DECRE_PRICE,
        UPDATE_PRICE_MOBILE_COST_SUFF_DECRE_PRICE,
        UPDATE_PRICE_MOBILE_TO_INCREASE_COST,
        UPDATE_PRICE_MOBILE_TO_DECREASE_COST,
        UPDATE_PRICE_MOBILE_NOCLICK_INCRE_PRICE,
        UPDATE_PRICE_MOBILE_ROI_PREDICT_GOOD_INCRE_PRICE,
        UPDATE_PRICE_MOBILE_CUSTOM,
        UPDATE_PRICE_MOBILE_WIDE_MATCH,
        UPDATE_PRICE_PC_WIDE_MATCH,
        SET_PC_KEYWORDS_MODEL,
        SET_WX_KEYWORDS_MODEL,
        UPDATE_WX_RANK_CPC_MAX,
        UPDATE_PC_RANK_CPC_MAX,
    ]

    ALL_KEYWORD_PC_UPDATE_TYPES = [
        UPDATE_PRICE_ROI_PREDICT_GOOD_INCRE_PRICE,
        UPDATE_PRICE_BUDGET_CONTROL_ORIGINAL_PRICE,
        UPDATE_PRICE_BUDGET_CONTROL_LOW_PRICE,
        UPDATE_PRICE_GOOD_POSITION_INCRE_PRICE,
        UPDATE_PRICE_GOOD_POSITION_DECRE_PRICE,
        UPDATE_PRICE_ROI_GOOD_INCRE_PRICE,
        UPDATE_PRICE_ROI_BAD_DECRE_PRICE,
        UPDATE_PRICE_COST_FULL_DECRE_PRICE,
        UPDATE_PRICE_GARBAGE_INCRE_PRICE,
        UPDATE_PRICE_NOCLICK_INCRE_PRICE,
        UPDATE_PRICE_MINIMIZE_CPC_MAX,
        UPDATE_PRICE_TO_INCREASE_COST,
        UPDATE_PRICE_TO_DECREASE_COST,
        UPDATE_PRICE_HISTORY_NORMAL,
        UPDATE_PRICE_CUSTOM,
        UPDATE_PRICE_FOR_CPC_MAX,
        UPDATE_PRICE_FOR_PC_CPC_MAX,
        UPDATE_PRICE_PC_WIDE_MATCH
    ]

    ALL_KEYWORD_WX_UPDATE_TYPES = [
        UPDATE_KEYWORD_MOBILE_PRICE_NORMAL,
        UPDATE_PRICE_FOR_WX_CPC_MAX,
        UPDATE_PRICE_MOBILE_ROI_GOOD_INCRE_PRICE,
        UPDATE_PRICE_MOBILE_ROI_BAD_DECRE_PRICE,
        UPDATE_PRICE_MOBILE_GARBAGE_INCRE_PRICE,
        UPDATE_PRICE_MOBILE_GOOD_POSITION_INCRE_PRICE,
        UPDATE_PRICE_MOBILE_GOOD_POSITION_DECRE_PRICE,
        UPDATE_PRICE_MOBILE_BUDGET_CONTROL_LOW_PRICE,
        UPDATE_PRICE_MOBILE_BUDGET_CONTROL_ORIGINAL_PRICE,
        UPDATE_PRICE_MOBILE_COST_FULL_DECRE_PRICE,
        UPDATE_PRICE_MOBILE_COST_SUFF_DECRE_PRICE,
        UPDATE_PRICE_MOBILE_TO_INCREASE_COST,
        UPDATE_PRICE_MOBILE_TO_DECREASE_COST,
        UPDATE_PRICE_MOBILE_NOCLICK_INCRE_PRICE,
        UPDATE_PRICE_MOBILE_ROI_PREDICT_GOOD_INCRE_PRICE,
        UPDATE_PRICE_MOBILE_CUSTOM,
        UPDATE_PRICE_MOBILE_WIDE_MATCH
    ]

    ALL_ADGROUP_DELETE_TYPES = [
        DELETE_ADGROUP_NORMAL,
        DELETE_ADGROUP_INITIAL,
        DELETE_ADGROUP_HISTORY_NORMAL
    ]

    ALL_ADGROUP_ADD_TYPES = [
        ADD_ADGROUP_NORMAL
    ]

    ALL_RULE_TYPES = [
        ADD_RULE,
        UPDATE_RULE,
        DELETE_RULE,
        ENABLED_RULE,
        DISABLED_RULE,
        EXECUTE_RULE,
        EXECUTE_RULE_NOTICE
    ]

OPTTYPE_COMMENT = {
    OperationType.DELETE_AUDIT_UNPASS: "关键词审核未通过，已经删除"
    , OperationType.DELETE_UNEXPECT: "关键词删除时未记录原因"
    , OperationType.DELETE_LOW_QSCORE : "关键词质量分过低，已经删除"
    , OperationType.DELETE_LOW_PV_OLD : "关键词最近一段时间展现量过低，已经删除"
    , OperationType.DELETE_DELETE_PERCENT : "关键词在计划中相对表现较差，已经删除"
    , OperationType.DELETE_LOW_CLICK_OLD : "关键词最近一段时间点击量过低，已经删除"
    , OperationType.DELETE_IS_GARBAGE : "关键词15天展现为0，已经删除"
    , OperationType.DELETE_USER_DELETE : "关键词被用户手工删除"
    , OperationType.DELETE_USER_DELETE_TAOBAO : "关键词被用户在直通车手工删除"
    , OperationType.DELETE_GARBAGE_MAX_PRICE : "7天无展现关键词，已经删除"
    
    , OperationType.DELETE_LOW_PV_MAX_PRICE : "关键词已经达到用户设置的最高出价，仍然没有展现，已经删除"
    , OperationType.DELETE_LOW_PV_BEST_POSITION : "关键词已经排在首页，仍然没有展现，已经删除"
    
    , OperationType.DELETE_FILTER_WORDS : "根据用户设置的过滤词，关键词已经删除"
    , OperationType.DELETE_LOW_RELEVANCE : "由于关键词相关性不佳，已经删除"
    , OperationType.DELETE_DIRECTOR : "加力计划优化，发现关键词表现不佳，已经删除"
    , OperationType.DELETE_HISTORY_NORMAL : "关键词已经被删除(历史记录未区分类型)"
    , OperationType.DELETE_LOW_PV_BY_ADGROUP_CPC : "关键词已经超出推广组cpc较多，仍然没有展现，已经删除"
    , OperationType.DELETE_LOW_CTR : "关键词点击率太低，已经删除"
    , OperationType.DELETE_LOW_ROI : "关键词ROI较低，已经删除"
    , OperationType.DELETE_LOW_CUST_SCORE : "关键词基础分太低，已经删除"
    , OperationType.DELETE_LOW_PV : "关键词全网展现低，已经删除"
    , OperationType.DELETE_IS_GARBAGE_BY_USER : "根据用户设置删除垃圾词"
    
    , OperationType.DELETE_MANUAL_ADGROUP: "手动计划自定义优化删除符合条件关键词"

    , OperationType.UPDATE_PRICE_ROI_GOOD_INCRE_PRICE : "关键词最近一段时间效果好于计划整体，加大投入"
    , OperationType.UPDATE_PRICE_ITEM_GOOD_INCRE_PRICE: "宝贝在计划中表现相对优异，适当加大投入"
    , OperationType.UPDATE_PRICE_ITEM_BAD_DECRE_PRICE: "宝贝在计划中表现相对较差，适当减小投入"
    , OperationType.UPDATE_PRICE_ROI_PREDICT_GOOD_INCRE_PRICE : "系统预估关键词ROI潜力较大，适当加大投入"
    , OperationType.UPDATE_PRICE_ROI_BAD_DECRE_PRICE : "关键词最近一段时间效果低于计划整体，减小投入"
    , OperationType.UPDATE_PRICE_COST_SUFF_INCRE_PRICE : "计划花费过低，根据报表，关键词加大投入"
    , OperationType.UPDATE_PRICE_COST_FULL_DECRE_PRICE : "计划花费过高，根据报表，关键词减小投入"
    , OperationType.UPDATE_PRICE_GARBAGE_INCRE_PRICE : "关键词长期无展现，加大投入"
    , OperationType.UPDATE_PRICE_NOCLICK_INCRE_PRICE : "关键词无点击，加大投入"
    , OperationType.UPDATE_PRICE_MINIMIZE_CPC_MAX : "关键词超出设置的最高点击单价，降低出价"
    , OperationType.UPDATE_PRICE_TO_INCREASE_COST : "为了加大计划投入，关键词进行价格调整"
    , OperationType.UPDATE_PRICE_TO_DECREASE_COST : "为了减小计划投入，关键词进行价格调整"
    , OperationType.UPDATE_PRICE_TO_APPROVE_ROI : "为了提高计划效果，关键词价格进行调整"
    , OperationType.UPDATE_PRICE_DIRECTOR : "为了优化加力计划效果，关键词价格进行调整"
    , OperationType.UPDATE_PRICE_HISTORY_NORMAL: "关键词价格进行调整(历史记录未区分类型)"
    , OperationType.UPDATE_KEYWORD_MOBILE_PRICE_NORMAL: "关键词无线价格进行调整(历史记录未区分类型)"
    , OperationType.UPDATE_PRICE_COST_LESS_THAN_LIMIT_INCRE_PRICE: "计划花费未达到最低花费设置，关键词加大投入"
    , OperationType.UPDATE_PRICE_CUSTOM: "在一定出价范围内，关键词价格进行调整"
    , OperationType.UPDATE_PRICE_FOR_CPC_MAX: "根据用户设置最高点击单价，调整关键词价格"
    , OperationType.UPDATE_PRICE_MOBILE_ROI_GOOD_INCRE_PRICE: "关键词最近一段时间无线效果好于计划整体，加大投入"
    , OperationType.UPDATE_PRICE_MOBILE_ROI_BAD_DECRE_PRICE: "关键词最近一段时间无线效果低于计划整体，减小投入"
    , OperationType.UPDATE_PRICE_MOBILE_GARBAGE_INCRE_PRICE: "关键词移动端长期无展现，加大投入"
    , OperationType.UPDATE_PRICE_MOBILE_GOOD_POSITION_INCRE_PRICE: "关键词通过加价获得一个移动端好排名"
    , OperationType.UPDATE_PRICE_MOBILE_GOOD_POSITION_DECRE_PRICE: "关键词通过减价获得一个移动端好排名"
    , OperationType.UPDATE_PRICE_MOBILE_BUDGET_CONTROL_LOW_PRICE: "推广组花费超过预算，进行预算控制，暂时关闭关键词移动端流量"
    , OperationType.UPDATE_PRICE_MOBILE_BUDGET_CONTROL_ORIGINAL_PRICE: "推广组预算控制清零，恢复关键词移动端价格到昨日原价"
    , OperationType.UPDATE_PRICE_BUDGET_CONTROL_LOW_PRICE: "推广组花费超过预算，进行预算控制，暂时关闭关键词PC流量"
    , OperationType.UPDATE_PRICE_BUDGET_CONTROL_ORIGINAL_PRICE: "推广组预算控制清零，恢复关键词PC价格到昨日原价"
    , OperationType.UPDATE_PRICE_MOBILE_COST_FULL_DECRE_PRICE: "计划移动花费过高，根据报表，关键词减小移动投入"
    , OperationType.UPDATE_PRICE_MOBILE_COST_SUFF_DECRE_PRICE: "计划移动花费过低，根据报表，关键词加大移动投入"
    , OperationType.UPDATE_PRICE_MOBILE_TO_INCREASE_COST : "为了加大计划投入，关键词进行移动价格调整"
    , OperationType.UPDATE_PRICE_MOBILE_TO_DECREASE_COST : "为了减小计划投入，关键词进行移动价格调整"
    , OperationType.UPDATE_PRICE_MOBILE_NOCLICK_INCRE_PRICE : "关键词无点击，加大移动端投入"
    , OperationType.UPDATE_PRICE_MOBILE_ROI_PREDICT_GOOD_INCRE_PRICE : "系统预估关键词ROI潜力较大，适当加大移动端投入"
    , OperationType.UPDATE_PRICE_MOBILE_CUSTOM: "在一定出价范围内，关键词移动价格进行调整"
    , OperationType.UPDATE_PRICE_MOBILE_WIDE_MATCH: "提升移动流量，关键词修改为广泛匹配"

    , OperationType.UPDATE_PRICE_PC_WIDE_MATCH: "提升PC流量，关键词修改为广泛匹配"
    , OperationType.UPDATE_PRICE_GOOD_POSITION_INCRE_PRICE : '关键词通过加价获得一个好排名'
    , OperationType.UPDATE_PRICE_GOOD_POSITION_DECRE_PRICE : '关键词通过减价获得一个好排名'
    , OperationType.UPDATE_PRICE_HOT_INCRE_CLICK_INCRE_PRICE : '测款计划通过加价增加流量'
    , OperationType.UPDATE_PRICE_HOT_DECRE_CLICK_DECRE_PRICE : '测款计划通过减价减少流量'
    , OperationType.UPDATE_PRICE_HOT_COST_FULL_DECRE_PRICE : '测款计划花费接近预算上限,关键词减价'
    , OperationType.UPDATE_PRICE_USER_EXPECT_INCRE_PRICE:'用户意图加大流量，关键词加价'
    , OperationType.UPDATE_PRICE_USER_EXPECT_DECRE_PRICE:'用户意图减小流量，关键词减价'
    , OperationType.UPDATE_PRICE_ACCURATE_MATCH: "点击率低，关键词修改匹配方式"
    , OperationType.UPDATE_PRICE_WIDE_MATCH: "提升流量，关键词修改为广泛匹配"
    , OperationType.KEEP_NORMAL : "检查了推广组所有关键词，由于推广组和关键词报表数据良好，价格无需调整"
    
    , OperationType.UPDATE_PRICE_MANUAL_ADGROUP: "手动计划自定义优化关键词价格"
    
    , OperationType.IGNORE_KEYWORD_NOT_EXIST: "关键词不存在"
    , OperationType.IGNORE_KEYWORD_NOT_HANDLE : "关键词未托管，无需处理"
    , OperationType.IGNORE_NOT_MANAGE_BY_SOFT : "关键词价格超出设置价格，无需处理"
    , OperationType.IGNORE_CREATE_TIME_SHORT : "关键词创建时间太短，无需处理"
    , OperationType.IGNORE_MODIFIED_TIME_SHORT : "关键词修改时间太短，无需处理"
    , OperationType.IGNORE_KEYWORD_REPORT_NONE : "关键词报表未能获取，无需处理"
    , OperationType.IGNORE_CAMPAIGN_REPORT_NONE : "关键词所在计划报表未能获取，无需处理"
    , OperationType.IGNORE_ADGROUP_REPORT_NONE: "关键词所在推广组报表未能获取，无需处理"
    , OperationType.IGNORE_CAMPAIGN_STOPPED: "关键词所在计划展现过低，无需处理"
    
    
    , OperationType.IGNORE_CAMPAIGN_OFFLINE: "计划已暂停,不处理"
    , OperationType.IGNORE_CAMPAIGN_SETTINGS_NONE: "计划设置为空,不处理"
    , OperationType.IGNORE_CAMPAIGN_INIT_FAILED: "计划初始化失败,不处理" 
    , OperationType.IGNORE_CAMPAIGN_CANCEL_OPTIMIZE: "计划已经取消托管,不进行优化"
    , OperationType.IGNORE_CAMPAIGN_LOW_IMPRESSIONS: "计划展现太低,不处理"
    , OperationType.IGNORE_ADGROUP_TOO_MUCH: "推广组太多,需减少一些再优化"
    
    , OperationType.ADD_NORMAL: "新增关键词"
    , OperationType.ADD_KEYWORD_NORMAL: "新增关键词"
    , OperationType.ADD_KEYWORD_INITIAL: "新增关键词"
    , OperationType.ADD_KEYWORD_DIRECTOR: "新增关键词"
    , OperationType.ADD_KEYWORD_HISTORY_NORMAL: "新增关键词(历史记录未区分类型)"
    , OperationType.ADD_KEYWORD_EXTRA_INFO: "根据附加词信息新增关键词"
    
    , OperationType.ADD_ADGROUP_NORMAL: "新增推广组"
    , OperationType.DELETE_ADGROUP_NORMAL: "用户删除推广组"
    , OperationType.DELETE_ADGROUP_INITIAL: "计划初始化，删除推广组"
    , OperationType.DELETE_ADGROUP_HISTORY_NORMAL: "删除推广组(历史记录未区分类型)"

    , OperationType.START_ADGROUP: "推广组开启推广"
    , OperationType.START_OPTIMIZE_ADGROUP: "推广组加入托管" 
    , OperationType.STOP_ADGROUP: "推广组取消推广"
    , OperationType.STOP_OPTIMIZE_ADGROUP: "推广组取消托管"
    , OperationType.START_OPTIMIZE_ADGROUP_ONLY_PRICE: "推广组开启价格优化"

    , OperationType.ADD_CAMPAIGN_NORMAL: "新建计划" 
    , OperationType.START_CAMPAIGN: "计划开启推广" 
    , OperationType.START_OPTIMIZE_CAMPAIGN: "计划加入托管"
    ,OperationType.START_OPTIMIZE_CAMPAIGN_ITEM_LABEL:'计划启动宝贝标签自动识别'
    , OperationType.STOP_CAMPAIGN: "计划暂停推广"
    , OperationType.STOP_OPTIMIZE_CAMPAIGN: "计划取消托管"
    ,OperationType.STOP_OPTIMIZE_CAMPAIGN_ITEM_LABEL:'计划取消宝贝标签自动识别'
    ,OperationType.START_ITEM_AUTO_STATUS:'开启宝贝自动识别'
    ,OperationType.STOP_ITEM_AUTO_STATUS:'暂停宝贝自动识别'
    ,OperationType.CHANGE_ITEM_LABEL:'宝贝标签切换'
    , OperationType.UPGRADE_CAMPAIGN: "加力计划升级为全能计划"
    , OperationType.IGNORE_PLATFORM_UNHANDLE :"平台优化未打开"
    , OperationType.IGNORE_PLATFORM_CAMPAIGN_CANCEL_OPTIMIZE :"计划未托管，分时和平台不需要优化"
    , OperationType.IGNORE_PLATFORM_CAMPAIGN_LOW_COST:"计划花费过低，平台不需要优化" 
    , OperationType.IGNORE_PLATFORM_CAMPAIGN_OFFLINE :"计划暂停推广，分时和平台不需要优化"
    , OperationType.IGNORE_SCHEDULE_UNHANDLE :"分时优化未打开"
    , OperationType.CAMPAIGN_SCHEDULE_OPTIMIZE:"对计划分时折扣进行优化" 
    , OperationType.CAMPAIGN_PLATFORM_OPTIMIZE:"对计划平台设置进行优化" 
    , OperationType.IGNORE_SCHEDULE_REPORT_FAILED:"获取店铺分时报表异常，跳过优化"
    , OperationType.IGNORE_PLATFORM_REPORT_FAILED:"计划平台报表获取异常，跳过优化"
    , OperationType.IGNORE_CAMPAIGN_PLATFORM_NORMAL:"平台设置正常，跳过优化"
    , OperationType.IGNORE_CAMPAIGN_BUDGET_OUT_LIMIT:"省油宝低价版计划日限额超过100元，放弃优化"
    , OperationType.IGNORE_CAMPAIGN_GIVE_UP:"放弃计划优化"
    , OperationType.IGNORE_CAMPAIGN_NO_ADGROUP:"计划内无推广组"
    , OperationType.IGNORE_SHOP_IN_DEBT:"店铺欠费"
    , OperationType.IGNORE_RT_OPTIMIZE_OFFLINE :"计划已下线,跳过实时优化"
    , OperationType.IGNORE_ADGROUP_NOT_INCREASE_COST: "不需要加大投入"
    , OperationType.IGNORE_ADGROUP_NOT_DECREASE_COST: "不需要减少投入"
    ,OperationType.CHANGE_CAMPAIGN_PLATFORM_PC_DISCOUNT:"调整pc平台折扣"
    ,OperationType.CHANGE_CAMPAIGN_PLATFORM_WX_DISCOUNT:"调整无线平台折扣"
    ,OperationType.OPEN_CAMPAIGN_PLATFORM_OPTIMIZE:"开启平台优化"
    ,OperationType.CLOSE_CAMPAIGN_PLATFORM_OPTIMIZE:"关闭平台优化"
    ,OperationType.ADD_NEW_CAMPAIGN_SETTINGS:"新设置自动计划"
    ,OperationType.RISE_ADGROUP_CPC_MAX:"为了效果加大投入,推广单元最高出价增加10%"
    ,OperationType.DROP_ADGROUP_CPC_MAX:"为了效果减少投入,推广单元最高出价减少10%"
    ,OperationType.CHANGE_CAMPAIGN_SETTINGS:"用户修改自动计划设置"
    ,OperationType.CHANGE_ADGROUP_SETTINGS:"用户修改推广组设置"
    ,OperationType.CHANGE_ADGROUP_MOBILE_DISCOUNT:"修改推广组移动折扣"
    ,OperationType.ADD_RULE:"新增"
    ,OperationType.UPDATE_RULE:"修改"
    ,OperationType.DELETE_RULE:"删除"
    ,OperationType.DISABLED_RULE:"暂停"
    ,OperationType.ENABLED_RULE:"开启"
    ,OperationType.EXECUTE_RULE:"执行"
    ,OperationType.EXECUTE_RULE_NOTICE:"自动执行"
    ,OperationType.CHANGE_CAMPAIGN_WX_CPC_MAX:"修改计划无线端最高出价"
    ,OperationType.CHANGE_ADGROUP_WX_CPC_MAX:"修改推广组无线端最高出价"
    ,OperationType.CHANGE_ADGROUP_BUDGET:"修改推广组预算"
    ,OperationType.UPDATE_PRICE_FOR_PC_CPC_MAX:"关键词根据用户设置PC最高出价进行调价"
    ,OperationType.UPDATE_PRICE_FOR_WX_CPC_MAX:"关键词根据用户设置无线最高出价进行调价"
    ,OperationType.START_CROWD_OPTIIMIZE:"开启推广组人群优化"
    ,OperationType.START_CROWD:"开启人群推广"
    ,OperationType.STOP_CROWD_OPTIMIZE:"暂停推广组人群优化"
    ,OperationType.STOP_CROWD:"暂停人群推广"
    ,OperationType.UPDATE_CROWD_DISCOUNT:"更新推广组人群溢价"
    ,OperationType.DELETE_CROWD:"删除人群"
    ,OperationType.ADD_CROWD:"增加人群"
    ,OperationType.FOLLOW_CAMPAIGN:"推广组设置跟随计划"
    ,OperationType.UPDATE_CAMPAIGN_BUDGET:"对计划日限额进行调整"
    ,OperationType.UPDATE_CAMPAIGN_MODEL:"修改计划推广平台"
    ,OperationType.SET_PC_KEYWORDS_MODEL:'计划改为pc模式调整无线关键词价格'
    ,OperationType.SET_WX_KEYWORDS_MODEL:'计划改为无线模式调整pc关键词价格'
    ,OperationType.UPDATE_WX_RANK_CPC_MAX:'修改抢排名关键词无线最高出价'
    ,OperationType.UPDATE_PC_RANK_CPC_MAX:'修改抢排名关键词PC最高出价'
    ,OperationType.DELETE_CREATIVE_NORMAL:'推广组创意删除'
    ,OperationType.ADD_CREATIVE_NORMAL:'推广组创意添加'
    ,OperationType.MODIFY_CREATIVE_NORMAL:'推广组创意修改'
}

class LoginFailType(object):
    UN_BUY = 1
    USER_NOT_EXIST = 2
    MERCHANT_TEST = 3
    DRAWBACK = 4
    SUBWAY_TOKEN_ERROR = 5
    NO_ITEM_CODE = 6
    NEED_MANAGER = 7
    ACCESS_TOKEN_ERROR = 8
    HTTP_ERROR = 9
    FORBBDIEN_DEBUG_PLATFROM= 10
    NO_SUBSCRIBE = 11
    UID_NOT_FOUND = 12
    NEED_TOP_AUTH = 13
    NO_SWITCH_PERMISSION = 14
    NO_JUMP_PERMMISSION = 15

class AdgroupHandleStatus(object):
    UNDEAL = 0
    AUTO_DEAL = 1
    ONLY_PRICE = 2

class FilterType(object):
    OFFLINE = 'offline_type'
    USER_CONFIRM = 'user_confirm'
    BAN = 'is_ban'
    USER_DELETE = 'is_user_delete'
    USER_BLACK = 'is_user_black'

    AUDIT_OFFLINE = 'audit_offline'
    CRM_OFFLINE = 'crm_offline'
    DISALLOW = 'disallow'
    UNKNOWN = 'unknown'
    FILTER = True

    ALL_FILTER_CODE = [AUDIT_OFFLINE,CRM_OFFLINE,DISALLOW,UNKNOWN,FILTER]

    ALL_FILTER_TYPE = {
        OFFLINE : [AUDIT_OFFLINE,CRM_OFFLINE],
        USER_CONFIRM : [DISALLOW,UNKNOWN],
        BAN : [FILTER],
        USER_DELETE : [FILTER],
        USER_BLACK :[FILTER]
    }

    FILTER_COMMENT = {
        (OFFLINE,AUDIT_OFFLINE):'审核下线'
        ,(OFFLINE,CRM_OFFLINE):'crm下线'
        ,(USER_CONFIRM,DISALLOW):'用户不同意推广'
        ,(USER_CONFIRM,UNKNOWN):'有风险,用户还未确认'
        ,(BAN,FILTER):'宝贝曾违规或审核失败'
        ,(USER_DELETE,FILTER):'不推广用户删除的宝贝'
        ,(USER_BLACK,FILTER):'用户添加到不推广名单中'
    }

    @classmethod
    def REASON(cls,type,value):
        if type in cls.ALL_FILTER_TYPE and value in cls.ALL_FILTER_TYPE[type]:
            return cls.FILTER_COMMENT[(type,value)]

LOGFAILTYPE_COMMENT = {
        LoginFailType.UN_BUY:'授权失败，当前用户未购买该软件，请切换淘宝帐号并重新登录，<a href="http://login.taobao.com/member/logout.jhtml?spm=1.1000386.5982201.5.qQ0uFL&f=top&out=true&redirectURL=http%3A%2F%2Fwww.taobao.com%2F">退出当前淘宝帐号</a>'
        ,LoginFailType.USER_NOT_EXIST:'用户不存在'
        ,LoginFailType.MERCHANT_TEST:'商家测试帐号无法登录'
        ,LoginFailType.DRAWBACK:'对不起, 该账户已经后台退款，不能继续使用软件'
        ,LoginFailType.SUBWAY_TOKEN_ERROR:'亲，无法查询到您的直通车帐号信息，请核对您的直通车帐号名和淘宝帐号名是否一致'
        ,LoginFailType.NO_ITEM_CODE:'系统暂时查不到您的订购记录，请尝试重新登录'
        ,LoginFailType.NEED_MANAGER:'进入后台失败，请先登录管理员账户'
        ,LoginFailType.ACCESS_TOKEN_ERROR:'授权失败，淘宝的access_token解析错误，请尝试重新登录'
        ,LoginFailType.HTTP_ERROR:'授权失败，与淘宝通信出错，请尝试重新登录'
        ,LoginFailType.FORBBDIEN_DEBUG_PLATFROM:'对不请,线上环境禁止debug登入,请从全拼域名的客服后台登入'
        ,LoginFailType.NO_SUBSCRIBE:'未找到订购关系,当前用户未购买软件或已退款'
        ,LoginFailType.UID_NOT_FOUND:'授权失败,关键性信息uid缺失'
        ,LoginFailType.NEED_TOP_AUTH:'需要OPEN授权'
        ,LoginFailType.NO_SWITCH_PERMISSION:'无权限切换用户，请尝试重新登录主账户'
        ,LoginFailType.NO_JUMP_PERMMISSION:'没有权限从CRM进入用户管理后台'
}
